name: Build and deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-18.4
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint:prod
